---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

image: "eclipse-temurin:17-jdk-alpine"

variables:
  GIT_DEPTH: "1"

cache:
  key: "cache-build"
  paths:
    - cache/build/
  when: "always"

before_script: |
  # Install dependencies
  apk add bash zip~=3.0 wget || exit "${?}"

include:
  # - template: Security/Dependency-Scanning.gitlab-ci.yml
  # - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  # - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test

# Disabled for now
.build-oss-job:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG && $CI_COMMIT_TAG != "nightly"
  cache: []
  script: "BUILD_TYPE='oss' './build.sh'"

build-job:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - "LICENSES/**/*"
        - "includes/common.sh"
        - "tools/**/*"
        - "zip-content/**/*"
        - ".gitlab-ci.yml"
        - "build.sh"
        - "conf-*.sh"
  script: "BUILD_TYPE='full' './build.sh'"
  artifacts:
    paths:
      - output/*.zip*
    expire_in: 30 minutes

# Cache expiration: 14 days
ping-cache:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
  before_script: []
  script: ":"

# license_scanning:
#   stage: test
#   artifacts:
#     paths:
#       - gl-license-scanning-report.json

# Disabled for now
sast:
  stage: test
  rules:
    - when: never
  cache: []
  before_script: []
