---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "Check app updates"
permissions: {}
on:
  push:
    paths:
      - ".github/workflows/check-app-updates.yml"
      - "includes/lib-check-app-updates.mjs"
      - "zip-content/origin/**"
      - "tools/test-check-updates.mjs"
  workflow_dispatch:
  schedule:
    # At 05:00 AM, every 7 days (UTC)
    - cron: "0 5 */7 * *"

jobs:
  check-updates:
    name: "Check updates"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read  # Needed to checkout the repository

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v6
        with:
          lfs: false
          sparse-checkout: |
            zip-content/origin
            includes/lib-check-app-updates.mjs
      - name: "Use LFS cache"
        uses: actions/cache/restore@v5
        timeout-minutes: 10
        with:
          key: "lfs-${{ hashFiles('conf-lfs.sh') }}"
          restore-keys: "lfs-"
          path: "cache/lfs"
          enableCrossOsArchive: true
      - name: "Check for updates in F-Droid and microG repos"
        uses: actions/github-script@v8
        timeout-minutes: 25
        with:
          retries: 1
          script: |
            const { default: run } = await import(
              `${process.env.GITHUB_WORKSPACE}/includes/lib-check-app-updates.mjs`
            );
            await run({ core });
