name: "Code linting"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "ShellChecker"
        uses: a5k-actions/shellchecker@main
        with:
          severity: "warning"
          ignore-files: "gradlew"
