---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "Code lint"
permissions: {}
on:
  push:
    paths:
      - "**"
    branches:
      - "**"
    tags:
      - "v*.*"
  pull_request:
jobs:
  shellchecker:
    name: "ShellChecker"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v5
      - name: "ShellChecker"
        uses: a5k-actions/shellchecker@v0

  reuse:
    name: "..."
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v5
      - name: "...."
        shell: bash
        run: |
          echo "_${GITHUB_HEAD_REF}_"
          echo "_${GITHUB_REF_NAME}_"

  json-yaml-validate:
    name: "JSON and YAML"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v5
      - name: "JSON and YAML - Validator"
        uses: GrantBirki/json-yaml-validate@v3
