name: Code validation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Gradle Wrapper validation
        uses: gradle/wrapper-validation-action@master
      - name: Remove gradlew (to avoid ShellCheck scan of it)
        run: rm -f gradlew
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          check_together: 'yes'
          severity: 'warning'
