name: Validations and checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Gradle Wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: ShellCheck
        uses: azohra/shell-linter@latest
        with:
          severity: 'error'
