---
# SPDX-FileCopyrightText: (c) 2024 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later

name: "Tools tester"
permissions: {}
on:
  push:
    paths:
      - ".github/workflows/tools-tester.yml"
      - "tools/**"
  pull_request:
    paths:
      - ".github/workflows/tools-tester.yml"
      - "tools/**"
  workflow_dispatch:

jobs:
  base:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-12
    name: "Tools test (${{ matrix.os }})"
    runs-on: "${{ matrix.os }}"

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
      - name: "Test script"
        shell: bash
        run: |
          # Testing script...
          printf '%s\n\n' 'bits-info.sh:'
          '${{ github.workspace }}/tools/bits-info.sh'
